# Generated by Django 5.2.3 on 2025-07-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('max_capacity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('publish_on', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
