# Generated by Django 5.2.3 on 2025-07-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_image_url_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_comment',
            name='image',
        ),
    ]
