# Generated by Django 5.2.3 on 2025-07-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sender',
            new_name='name',
        ),
    ]
